// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AwaitReady() {
  return window['go']['application']['App']['AwaitReady']();
}

export function Greet(arg1) {
  return window['go']['application']['App']['Greet'](arg1);
}
